### ISSUE TITLE
Custom QR code shortcode for ticket template

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-ticketing#8]
## Issue Overview

This would allow for including a QR code with custom data (instead of the default QR code that only outputs the REG CODE). This is useful in cases where the event manager wants a QR code for other purposes besides scanning for check-in. 

See also: https://eventespresso.com/wiki/custom-qr-codes-for-tickets/
Note that Google's Chart API is officially end of life. 

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by nerrad** [comment]
We definitely can implement something here, but I'd like to work out some ui/ux around this first.

- what string should the custom qrcode have (`[CUSTOM_QR_CODE_*`])?
- I think there are some limits to how much data the qrcode can contain dependent on type (see chart here https://kazuhikoarase.github.io/qrcode-generator/js/demo/ for number of bytes).  Do we want to add some validation for those limits - tricky because it may mean parsing any shortcodes used as a value for the code to get what they render to).  Or should we just make sure we document those limits and encourage people to test?
- Should the custom code be distinguished a bit from the default registration qr code shortcode in any output?  Or should we leave that up to the user to how they do things?
- Should we expose the same same options as we do as the existing shortcode?

**Comment by joshfeck** [comment]
Stalebot, and customer in the forums both reminded me of this.

With regards to UI, what about adding a new section? This way instead of a * followed by content (which could presumably include shortcodes) it's just a section in the ticket template editor, and you place the [CUSTOM_QR_CODE] shortcode where you want the qr code to display.

With regards to limits, let's document the limit and truncate any extra characters sent to the QR code at output.

> Should we expose the same same options as we do as the existing shortcode?
Yes.
> Should the custom code be distinguished a bit from the default registration qr code shortcode in any output?
Since we're exposing the same options as the existing shortcode, could we set a default for this shortcode's "label" option so it defaults to "Additional Information"?

**Comment by nerrad** [comment]
> With regards to UI, what about adding a new section? This way instead of a * followed by content (which could presumably include shortcodes) it's just a section in the ticket template editor, and you place the [CUSTOM_QR_CODE] shortcode where you want the qr code to display.

Are you talking about an entirely new field in the editor?  If so, I'm wary of doing this because it increases the scope of work for this issue (adding a new field affects existing templates more, as well as potentially existing documentation).

**Comment by joshfeck** [comment]
OK you can scratch that idea then

**Comment by joshfeck** [comment]
Just noting that the Charts API is deprecated (not end of life).
